#pragma once
typedef int esp_err_t;
enum { ESP_OK, ESP_FAIL, ESP_ERR_INVALID_ARG, ESP_ERR_INVALID_STATE,
       ESP_ERR_NOT_FOUND, ESP_ERR_INVALID_RESPONSE, ESP_ERR_INVALID_SIZE, ESP_ERR_NO_MEM,
       ESP_ERR_TIMEOUT, ESP_ERR_INVALID_CRC, ESP_ERR_NOT_ALLOWED };
