#pragma once

#include "driver/gpio.h"
#include "driver/spi_master.h"

#define BOARD_NAME "Waveshare ESP32-S3-RLCD-4.2"

#define BOARD_DISPLAY_WIDTH 400
#define BOARD_DISPLAY_HEIGHT 300
#define BOARD_DISPLAY_MOSI_GPIO GPIO_NUM_12
#define BOARD_DISPLAY_SCLK_GPIO GPIO_NUM_11
#define BOARD_DISPLAY_DC_GPIO GPIO_NUM_5
#define BOARD_DISPLAY_CS_GPIO GPIO_NUM_40
#define BOARD_DISPLAY_RESET_GPIO GPIO_NUM_41
#define BOARD_DISPLAY_SPI_HOST SPI3_HOST
#define BOARD_DISPLAY_SPI_CLOCK_HZ 24000000

#define BOARD_I2C_SDA_GPIO GPIO_NUM_13
#define BOARD_I2C_SCL_GPIO GPIO_NUM_14
#define BOARD_I2C_CLOCK_HZ 100000

#define BOARD_AUDIO_MCLK_GPIO GPIO_NUM_16
#define BOARD_AUDIO_BCLK_GPIO GPIO_NUM_9
#define BOARD_AUDIO_WS_GPIO GPIO_NUM_45
#define BOARD_AUDIO_DIN_GPIO GPIO_NUM_10
#define BOARD_AUDIO_DOUT_GPIO GPIO_NUM_8
#define BOARD_AUDIO_PA_GPIO GPIO_NUM_46
#define BOARD_AUDIO_ES8311_I2C_ADDRESS 0x18
#define BOARD_AUDIO_ES7210_I2C_ADDRESS 0x40

#define BOARD_BATTERY_ADC_GPIO GPIO_NUM_4
#define BOARD_BOOT_GPIO GPIO_NUM_0
#define BOARD_KEY_GPIO GPIO_NUM_18
